services:
  laravel:
    image: pictureapp-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql

  chat-server:
    image: pictureapp-chat
    ports:
      - "3001:3001"

volumes:
  mysql_data:
