services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  chat-server:
    build: ./chat-server
    ports:
      - "3002:3001"
    environment:
      LARAVEL_API_URL: "http://laravel:8000"
      LARAVEL_API_TOKEN: "SOME_SERVICE_TOKEN"
    depends_on:
      - laravel
      - mysql
    restart: always

volumes:
  db_data:

