name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Laravel image
        run: |
          docker build -t pictureapp-laravel ./backend

      - name: Build Chat Server image
        run: |
          docker build -t pictureapp-chat ./chat-server

      - name: Save Laravel image to archive
        run: docker save pictureapp-laravel | gzip > laravel.tar.gz

      - name: Save Chat Server image to archive
        run: docker save pictureapp-chat | gzip > chat.tar.gz

      - name: Upload deployment files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "laravel.tar.gz,chat.tar.gz,deploy.sh,docker-compose.prod.yml"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Run deployment script on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            chmod +x deploy.sh
            ./deploy.sh
